name: deploy
on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bump Version
        id: bump
        uses: Plugily-Projects/maven-version-bump-action@dev
        with:
          github-token: ${{ secrets.github_token }}
          repo-build: MAVEN
          auto-version-bump: true
          git-committer: 'BOT'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk

      - name: maven-settings-action
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
                "id": "${{ secrets.PLUGILY_REPO_ID }}",
                "username": "${{ secrets.PLUGILY_REPO_USERNAME }}",
                "password": "${{ secrets.PLUGILY_REPO_PASSWORD }}"
            }]

      - run: mvn clean verify compile package site:site javadoc:javadoc javadoc:jar deploy -f pom.xml
